// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://7tonsmaxfzboliporvia3gw7ey.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ewcoxwk66zdmxnq3n2rieyj43y",
    "aws_cognito_identity_pool_id": "us-east-1:3d1f79e9-8c6a-434d-9dd0-fa6d2afaf1f2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aNuq8bi2G",
    "aws_user_pools_web_client_id": "2gikh6vg29vn2a33qmjr26sr6g",
    "oauth": {}
};


export default awsmobile;
